# @package _global_
# These are the default values for the algorithm hyper-parameters when using the example algorithm
# with the SimpleVGG architecture on the CIFAR10 dataset.
algorithm:
  feedback_noise_std: 0.3395
  feedback_optim:
    lr: 0.0647
    weight_decay: 3.486e-05
  # feedback_training_iterations: 19 # NOTE: Tuning found '19' as the best value, turning it down.
  feedback_training_iterations: 1
  forward_optim:
    lr: 0.0003721
    weight_decay: 1.529e-05
  n_noise_samples: 16
